## 异常

try与catch里面都可以再套try与catch

```java
public static void main(String[] args) throws IOException {
        
        File file = new File("D.//aa.txt");
        FileWriter fw = new FileWriter(file);/* 异常可以向外抛出  但是调用方法时就需要解决我抛出的异常  可以try-catch  也可以继续向外面抛*/
        
        String str = "kjjj";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");

        Date date = null;
        try {
            date = simpleDateFormat.parse(str);
            //上面异常了，下面不执行
            System.out.println(date);
        } catch (ParseException e) {
            System.out.println(e.getMessage());
            System.out.println("异常");
        }catch (NullPointerException e)
        {
            System.out.println(e.getMessage());
        }finally {
            //可能上面有异常没有捕获到，后面就不会执行了
            System.out.println("不管有没有异常，都会执行");
        }
        System.out.println("正常执行");
    }public static void main(String[] args) {
    String str = "kjjj";

    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");

    Date date = null;
    try {
        date = simpleDateFormat.parse(str);
        //上面异常了，下面不执行
        System.out.println(date);
    } catch (ParseException e) {
        System.out.println(e.getMessage());
        System.out.println("异常");
    }catch (NullPointerException e)
    {
        System.out.println(e.getMessage());
    }finally {
        //可能上面有异常没有捕获到，后面就不会执行了
        System.out.println("不管有没有异常，都会执行");
    }

    System.out.println("正常执行");
}
```





RunTimeException要在Exception前面

越高级(父类)的异常越靠后





**如果抛出的是RunTimeException（或其之类）   调用方法是就不用try-catch 或抛出异常**





## throw与throws

注意与throws的区别

throw是异常new对象

```java
public static void add(int age)
{
    if(age<0)
    {
        throw new IllegalArgumentException("年龄不可为负");
    }
}
```

运行时异常   throw  不用往外抛





编译时异常   throw   要往外抛  会有throws

```java
public static void s(File file) throws FileNotFoundException {
    if (!file.exists()) {
        throw new FileNotFoundException("文件不存在: " + file.getAbsolutePath());
    }
}
```



***区别：***

throws用在方法声明上，抛出异常类型

throw用在方法声明中，抛出异常对象





## 自定义异常

1.自己建一个异常类，继承与Exception（要抛出throws）或RunTimeException（不用抛出throws）

2.添加需要的构造方法

```java
public class MyException extends RuntimeException{
    public MyException() {
    }

    public MyException(String message) {
        super(message);
    }
}
```



3.进行使用

```java
public class MainMyException {
    public static void main(String[] args) {
        //输入一个手机号码
        String phone = "xxxx";
        checkPhone(phone);
    }

    public static void checkPhone(String phone){

        String regex ="^1[3-9][0-9]{9}";
        if(!phone.matches(regex)){
            throw  new MyException("手机号码格式不正确");
        }
    }
}
```

